//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmes
    {
        public string Nome { get; set; }
        public string Genero { get; set; }
        public string Faixa_Etaria { get; set; }
        public string Duracao { get; set; }
    }
}
